version: '3.8'

services:
  mysql-master:
    image: mysql:5.7
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    volumes:
      - mysql-master-data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --server-id=1 --log-bin=mysql-bin

  mysql-slave1:
    image: mysql:5.7
    container_name: mysql-slave1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    volumes:
      - mysql-slave1-data:/var/lib/mysql
    ports:
      - "3307:3306"
    depends_on:
      - mysql-master
    command: --server-id=2 --relay-log=mysql-relay-bin --log-slave-updates=1 --read-only=1

  mysql-slave2:
    image: mysql:5.7
    container_name: mysql-slave2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    volumes:
      - mysql-slave2-data:/var/lib/mysql
    ports:
      - "3308:3306"
    depends_on:
      - mysql-master
    command: --server-id=3 --relay-log=mysql-relay-bin --log-slave-updates=1 --read-only=1

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  php:
    image: php:7.4-apache
    container_name: php
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html

  nodejs:
    image: node:latest
    container_name: nodejs
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"

volumes:
  mysql-master-data:
  mysql-slave1-data:
  mysql-slave2-data:
  mongodb-data:
